### ISSUE TITLE
Clarify scope table modification policy

### ISSUE THREAD

**Issue by caniszczyk** [opencontainers/tob#10]
There's been confusion on how to directly update the scope table:
https://www.opencontainers.org/governance/oci-scope-table

Lets come up with a proposal to clarify the last section:

> MECHANISM FOR ADDING “ROWS” TO THIS TABLE
> 
> The appropriate mechanism for adding, removing or modifying rows to this table (e.g. creating a proposal for an additional optional layer) is to bring it before the TDC. The TOB can be a source of appeal and/or can discuss if there isn’t a clear consensus in the TDC.

**Comment by diogomonica** [comment]
@caniszczyk I think the scope table is a fundamental part of the governance docs, since it lays out clearly what was agreed as part of this initiative, and was was not.

In particular, it is clearly stated in the governance docs that the mission of OCI is not to create a complete stack:

> OCI container format specification*. While the mission of OCI is not to create a complete stack, the format and runtime will:

Without that table laying out exactly what this meant, and what should be base/optional layers, this would have been too vague.

**Comment by caniszczyk** [comment]
@diogomonica if we consider the scope table part of the governance docs, then section 12 of the charter would apply to updates: https://www.opencontainers.org/about/governance

If that's the intention, I'm fine, I'm just looking for newly proposed wording in that section that the TOB can agree on so we are clear how the scope table can be amended.

**Comment by vbatts** [comment]
If the scope table had intentions of being under the same process as the charter, then it would say such, but it only has reference to TDC approval. These appear quite like distinct processes. I'm really not seeing the issue.

**Comment by diogomonica** [comment]
Any updates on this clarification effort?

**Comment by estesp** [comment]
Seems this is moot given the removal of the scope table in #74

**Comment by caniszczyk** [comment]
scope table is removed
