### ISSUE TITLE
Reference types working group onboarding

### ISSUE THREAD

**Issue by lachie83** [opencontainers/tob#105]
This is the tracking issue for the onboarding administrative tasks for the Reference types working group:

Related issues/PRs
* https://github.com/opencontainers/tob/issues/96
* https://github.com/opencontainers/tob/pull/103

cc @justincormack @dmcgowan @jonjohnsonjr @michaelb990

- [x] Merge proposal PR - https://github.com/opencontainers/tob/pull/103
- [x] Request TOB creation of a new repo (suggest wg-reference-types) under the OCI GH org with proposed owners in the proposal to have approve and merge access
- [x] Create WG README (similar to [this](https://github.com/kubernetes/community/blob/master/wg-api-expression/README.md)) in the new repo
- [x] Create slack channel wg-reference-types in OCI slack
- [x] Create mailing list
- [ ] Assign TOB liaison (optional)
- [x] Send out Doodle to schedule WG meeting
- [x] Setup Zoom schedule and provide access to proposed owners

**Comment by caniszczyk** [comment]
regarding mailing list, may I suggest to use github discussions?

@amye will handle onboarding of the WG

**Comment by caniszczyk** [comment]
https://github.com/opencontainers/wg-reference-types/discussions

**Comment by amye** [comment]
To keep things simple, I've created a recurring meeting for this in our normal Zoom account, and it's set to automatically record.

**Comment by amye** [comment]
@lachie83 - happy to set up a Doodle for folks, thinking sending in the week of January 3rd is best?

**Comment by lachie83** [comment]
Thanks so much @amye @caniszczyk 

> To keep things simple, I've created a recurring meeting for this in our normal Zoom account, and it's set to automatically record.

How do we get access to the Zoom meeting link?

> happy to set up a Doodle for folks, thinking sending in the week of January 3rd is best?

Can we try for the week of the 11th just to give folks a chance to recompress into 2022.

**Comment by amye** [comment]
> Thanks so much @amye @caniszczyk
> 
> > To keep things simple, I've created a recurring meeting for this in our normal Zoom account, and it's set to automatically record.
> 
> How do we get access to the Zoom meeting link?

I'll wake up the zoom as we get a meeting time, just know it's out there! 
> 
> > happy to set up a Doodle for folks, thinking sending in the week of January 3rd is best?
> 
> Can we try for the week of the 11th just to give folks a chance to recompress into 2022.

Totally. Sending the week of the 3rd with times and dates for the 11th, and we'll see where we land!

**Comment by amye** [comment]
Ok, back and thinking through this: 
(1) Doodle: This should likely go to tob@ and dev@ lists to get the maximum amount of people interested in this. 
(2) Timezones: Thinking of keeping the initial poll to just US times to keep things manageable. @lachie83 - anything I'm missing?

**Comment by amye** [comment]
https://doodle.com/poll/4z8s3bpgqdmg4c49 is live, will go out to lists shortly. :)

**Comment by lachie83** [comment]
> (2) Timezones: Thinking of keeping the initial poll to just US times to keep things manageable. @lachie83 - anything I'm missing? 

No I think that's it. Thanks @amye

**Comment by amye** [comment]
I see an agenda item for today's meeting for 'finalize mission statement', which is what the README is dependent on.
When that comes through, we'll be able to complete this.

**Comment by lachie83** [comment]
WG Readme landed here - https://github.com/opencontainers/wg-reference-types/blob/main/README.md

**Comment by lachie83** [comment]
I think we can close this for now and if TOB liaisons are needed we work with the TOB on assigning them

**Comment by lachie83** [comment]
Confirmed with Vincent that recordings are being posted to Youtube
