### ISSUE TITLE
Add 'runtime-tools' and 'image-tools' as official projects

### ISSUE THREAD

**Issue by caniszczyk** [opencontainers/tob#11]
This issue was brought up at an OCI Certification Working Group.

Should it just share the runtime-spec MAINTAINERS or do we select a new set?

We don't need to address this immediately, but it's something we should get clarity on it in the future.

**Comment by caniszczyk** [comment]
cc: @RobDolinMS 

Let me know when you have your proposal sketched out, I'd love for the TOB to vote on this so we can make it official.

**Comment by wking** [comment]
On Mon, Aug 22, 2016 at 07:52:13AM -0700, Chris Aniszczyk wrote:
> cc: @RobDolinMS 
> 
> Let me know when you have your proposal sketched out…

I think v1 of the proposal is [1,2].

[4]: https://github.com/RobDolinMS/tob/commit/4fa747360729bc9c588ce78b2382fa3f59bc14f5
[5]: https://groups.google.com/a/opencontainers.org/d/msg/dev/Y9CcSzCA-1Y/0HWZAdt7AQAJ
     Subject: RE: Agenda for 6/15
     Date: Wed, 15 Jun 2016 16:37:29 +0000
     Message-ID: <BY2PR0301MB1608A853DF9ABEA5BA2084CADE550@BY2PR0301MB1608.namprd03.prod.outlook.com>

**Comment by caniszczyk** [comment]
At the last OCI dev F2F, the TDC decided to come up with a two project approach:
https://docs.google.com/document/d/1bsi9JCnmOMSZCDh3VmDCO1m17w1aNexX09naomcpUOs/edit

Repo: ocitools → runtime-tools
Maintainers: Add Mrunal (RH) and Liang Chenye (Huawei)
New Repo: image-tools (populated by github.com/iopencontainers/image-spec/cmd/oci-image-tool)
Maintainers: Add Serge (CoreOS), Add Antonio (RH)

@RobDolinMS do you have anything else to add before we have the TOB vote this in?

**Comment by wking** [comment]
On Thu, Aug 25, 2016 at 05:06:06AM -0700, Chris Aniszczyk wrote:
> Repo: ocitools → runtime-tools

I'd rather use oci-{project}-tools [1].

[1]: https://github.com/RobDolinMS/tob/commit/4fa747360729bc9c588ce78b2382fa3f59bc14f5#commitcomment-18712958

**Comment by RobDolinMS** [comment]
Latest draft at: https://github.com/RobDolinMS/tob/blob/master/proposals/tools.md

**Comment by wking** [comment]
On Fri, Aug 26, 2016 at 06:20:33PM -0700, Rob Dolin (MSFT) wrote:
> Latest draft at: https://github.com/RobDolinMS/tob/blob/master/proposals/tools.md

This looks pretty good to me, although I left a few suggestions inline
in [1].  It might be easier to keep track of discussion on this
proposal if you filed a PR agsinst this repository.

[1]: https://github.com/RobDolinMS/tob/commit/c1a42654c54946ea1427583c6bfb61ae6b0e1dd6

**Comment by caniszczyk** [comment]
@RobDolinMS can you issue a PR? I think then @philips can call a vote on the TOB mailing list

**Comment by caniszczyk** [comment]
This was done: https://github.com/opencontainers/tob/blob/master/proposals/tools.md
