### ISSUE TITLE
Contacting the TOB

### ISSUE THREAD

**Issue by nishakm** [opencontainers/tob#110]
There are currently 3 avenues for engaging with the TOB: mailing list (tob@opencontainers.org I believe), GitHub issues, and meetings.

Is there a preference? My vote is for GitHub issues first, mailing list second, and meetings third.

**Comment by caniszczyk** [comment]
mailing list + gh team imho https://github.com/orgs/opencontainers/teams/tob/members

If you need to ping the @opencontainers/tob you can simply do that, but my advice is to keep everything on github if you can
