### ISSUE TITLE
OCI TOB Election 2023

### ISSUE THREAD

**Issue by caniszczyk** [opencontainers/tob#118]
A new year means a new election:

* Call for Nominations will open on Monday, November 7th and end on Wed November 30th.
* Call for Votes will open Thu, December 1st and end on Monday, December 12th.
* Vote winner will be announced on Monday, January 23rd (terms start on the 29th).

Each TDC maintainer may nominate up to two (2) candidates for election, except that only one (1) nominee may be employed by the TDC maintainer’s own company, which they are then voted upon by existing TDC maintainers. Here are the relevant sections from the OCI charter:
https://www.opencontainers.org/about/governance

> e. The TOB shall be composed of nine (9) individuals elected for their expertise, contribution to the advancement of container technologies and are considered to be thought leaders in the OCI ecosystem. Anyone may be elected to the TOB, regardless of whether the individual is an employee of an OCI Member, so long as they are an OCI TDC participant. A TOB member is elected as an individual and not as a representative of his or her employer. No more than two (2) TOB members may be employed by the same entity or its affiliates. Affiliates shall be defined as entities owning 50% or more of an entity, or owned by or under common ownership with each other. TOB members may not designate alternative representatives.
> 
> f. TOB members shall be split into two (2) groups, serving for a term of two (2) years on a staggered basis, where one group is elected each year. The initial TOB will have four (4) TOB members who will only serve for a term of one year and five (5) TOB members that serve for a term of two (2) years.
> 
> g. The initial TOB shall be established through a nomination and election process. The first group from which four (4) TOB members shall be elected, will be nominated and elected by the current TDC maintainers, initially identified in Section 4(e), and serve for a period of one (1) year. Each TDC maintainer may nominate up to two (2) candidates for election, except that only one (1) nominee may be employed by the TDC maintainer’s own company. The second group from which five (5) TOB members shall be elected, will be nominated and elected by the OCI Members and serve for a period of two (2) years. Each OCI Member may nominate one (1) candidate for election.

**Comment by caniszczyk** [comment]
Election form for TDC maintainers: https://forms.gle/7UnBf46coxR8mQ3t7

These are the TOB member seats that are expiring:

* Tycho Andersen [Cisco] (term date: 1/29/2021 - 1/29/2023)
* Vincent Batts [Microsoft] (term date: 1/29/2021 - 1/29/2023)
* Derek McGowan [Apple] (term date: 1/29/2021 - 1/29/2023)
* Aleksa Sarai [SUSE] (term date: 1/29/2021 - 1/29/2023)

**Comment by caniszczyk** [comment]
Just a friendly reminder for the @opencontainers/tob +

@opencontainers/image-spec-maintainers @opencontainers/runtime-spec-maintainers @opencontainers/runc-maintainers @opencontainers/umoci-maintainers @opencontainers/distribution-spec-maintainers @opencontainers/selinux-maintainers @opencontainers/image-tools-maintainers

**Comment by amye** [comment]
Last call on this, we'll be closing nominations today!

**Comment by amye** [comment]
Nominations are closed, congrats to our nominees: (alphabetical by first name)
Aleksa Sarai
Brandon Mitchell
Derek McGowan
Giuseppe Scrivano
Jason Hall
Mrunal Patel
Ramkumar Chinchani
Tycho Andersen
Vanessa Sochat
Vincent Batts

**Comment by amye** [comment]
Ballots are out, I will send opt-in messages to the addresses who have not yet opted in for CIVS voting.

**Comment by caniszczyk** [comment]
FYI the elected folks for the @opencontainers/tob election for 2023 are:

* Aleksa Sarai
* Brandon Mitchell
* Derek McGowan
* Vincent Batts 

Thanks to everyone who ran in the election and served!

We will get a blog post out on the 29th when the terms change!

**Comment by caniszczyk** [comment]
officially closed!

https://opencontainers.org/posts/blog/2023-01-26-oci-in-2023/

Thanks all!
