### ISSUE TITLE
Elect OCI TOB Chair 2023

### ISSUE THREAD

**Issue by caniszczyk** [opencontainers/tob#124]
The @opencontainers/tob needs to elect a new chair for 2023!

Is anyone from the @opencontainers/tob interested in running?

@samuelkarp would you like to stand again?

**Comment by samuelkarp** [comment]
@caniszczyk Sure, I'm happy to stand again.

**Comment by caniszczyk** [comment]
Thanks @samuelkarp 

I'll leave nominations open until end of day Friday, if any other @opencontainers/tob member wants to stand, otherwise @samuelkarp will continue in his role.

**Comment by vbatts** [comment]
On 31/01/23 07:00 -0800, Chris Aniszczyk wrote:
>Thanks @samuelkarp
>
>I'll leave nominations open until end of day Friday, if any other @opencontainers/tob member wants to stand, otherwise @samuelkarp will continue in his role.

I'm happy to see Samuel chair.
I'd offer my neck otherwise. :-D

**Comment by caniszczyk** [comment]
@samuelkarp will remain as chair since no one else stepped forward!

Thanks all!
