### ISSUE TITLE
Repo needed for wg-auth

### ISSUE THREAD

**Issue by sudo-bmitch** [opencontainers/tob#127]
The auth working group would like a repo to gather their work (similar to the [wg-reference-types](https://github.com/opencontainers/wg-reference-types)). From the [proposal](https://github.com/opencontainers/tob/blob/main/proposals/wg-auth.md), I think it would be good to have the following initial maintainers:

- Brandon Mitchell (@sudo-bmitch)
- Jason Hall (@imjasonh)
- Jeff Carter (@jcarter3)
- Mike Brown (@mikebrow)
- Ramkumar Chinchani (@rchincha)
- Toddy Mladenov (@toddysm)

**Comment by caniszczyk** [comment]
done!
