### ISSUE TITLE
Repo needed for wg-image-compatibility

### ISSUE THREAD

**Issue by sudo-bmitch** [opencontainers/tob#132]
The image compatibility working group is getting spun up, and I expect they'll need a repo.

Here's the [link to the proposed owners](https://github.com/opencontainers/tob/blob/main/proposals/wg-image-compatibility.md#proposed-owners). There's a lot of names in there, I'm happy to send out invites to anyone that's not already part of the OCI organization if that helps.

**Comment by amye** [comment]
Sure, what namespace do you need?

**Comment by amye** [comment]
I made you https://github.com/opencontainers/wg-image-compatibility after I realized the typo in this issue, I gave it the standard OCI projects template which isn't exactly right but isn't exactly wrong either.

**Comment by sudo-bmitch** [comment]
Typos are how you know I'm not an LLM. :)

Looking at how [wg-auth](https://github.com/opencontainers/wg-auth) was setup, I think Chris made mostly a blank repo (empty readme, standard license) and we filled it in from there mostly copying content from the referrers working group. Maybe we need a new template for working groups based off that minimal content? If someone creates a working-group-template repo, I'm happy to submit PRs over there for generic content that these all have in common.

For access, it looks like there's a team setup for maintainers, and then someone is assigned an admin role directly. I'm happy to handle any of the admin stuff if no one else wants it.

**Comment by amye** [comment]
Oh, yeah, @sudo-bmitch  - a template for wg would be splendid!
