### ISSUE TITLE
Repo needed for wg-freebsd-runtime

### ISSUE THREAD

**Issue by dfr** [opencontainers/tob#138]
It would be very useful for coordinating the work of defining a FreeBSD extension to the OCI runtime.

Proposed owners are listed [here](https://github.com/opencontainers/tob/blob/main/proposals/wg-freebsd-runtime.md#proposed-owners) - only @samuelkarp is currently part of the OCI organization.

**Comment by samuelkarp** [comment]
@amye Can you help with this?

**Comment by sudo-bmitch** [comment]
Heads up that https://github.com/opencontainers/wg-template/pull/2 should probably be merged first.

**Comment by amye** [comment]
https://github.com/opencontainers/wg-freebsd-runtime is up and running
