### ISSUE TITLE
Request: create a GitHub team for security-announce@opencontainers.org  subscribers

### ISSUE THREAD

**Issue by AkihiroSuda** [opencontainers/tob#142]
@caniszczyk @amye 

Could you create a GitHub team for security-announce@opencontainers.org  subscribers so that they be invited into private GHSA advisory pages? 🙏

**Comment by amye** [comment]
Done, you have access

**Comment by AkihiroSuda** [comment]
Thank you, could you invite the subscribers to the team? (I don’t have a permission)

**Comment by amye** [comment]
Drop me an email at amye@linuxfoundation.org, there's some.. complicating factors.

**Comment by AkihiroSuda** [comment]
Sure, sent an email
