### ISSUE TITLE
OCI TOB Elections for 2017

### ISSUE THREAD

**Issue by caniszczyk** [opencontainers/tob#20]
FYI @opencontainers/tob, just a friendly reminder that some 4 spots will open up in the TOB early next year: 

* (TOB Chair) Brandon Philips (start date: 1/29/2016 - term: 2 years)
* Michael Crosby (start date: 1/29/2016 - term: 1 year)
* Dr. Diogo Monica (start date: 1/29/2016 - term: 2 years)
* Jason Bouzane (start date: 1/29/2016 - term: 2 years)
* Greg Kroah-Hartman (start date: 1/29/2016 - term: 1 year)
* John Gossman (start date: 1/29/2016 - term: 2 years)
* Pavel Emelyanov (start date: 1/29/2016 - term: 1 year)
* Chris Wright (start date: 1/29/2016 - term: 2 years)
* Vincent Batts (start date: 1/29/2016 - term: 1 year)

@crosbymichael, @gregkh, @xemul and @vbatts spots will open up. They are free to nominate themselves and run again though if they so wish. A simple reminder that nominations will come from the TDC maintainers (everyone in a MAINTAINERS file).

> "The first group from which four (4) TOB members shall be elected, will be nominated and elected by the current TDC maintainers, initially identified in Section 4(e), and serve for a period of one (1) year"

> "Anyone may be elected to the TOB, regardless of whether the individual is an employee of an OCI Member, so long as they are an OCI TDC participant. A TOB member is elected as an individual and not as a representative of his or her employer." 

We will also elect a new TOB chair directly afterwards and by Feb 11th.

My proposed schedule is this:
* Dec 19th 2016 (Nominations Open)
* Jan 16th 2017 (Nominations Close)
* Jan 17th 2017 (Voting Opens)
* Jan 27th 2017 (Voting Closes)
* Jan 30th 2017 (Announce Winners)

Let me know if you have any comments.

**Comment by caniszczyk** [comment]
cc: @opencontainers/runc-maintainers @opencontainers/image-spec-maintainers @opencontainers/image-tools-maintainers @opencontainers/runtime-spec-maintainers @opencontainers/runtime-tools-maintainers

**Comment by vbatts** [comment]
SGTM

**Comment by philips** [comment]
@caniszczyk Where do nominations go again? I forget the process.

**Comment by caniszczyk** [comment]
@philips I'll simply create a google form or just use a github issue, let me know if you have a strong preference

**Comment by philips** [comment]
no preference

**Comment by caniszczyk** [comment]
@philips we'll use a google form, it's a bit easier to track data that way, I'll shoot an email to dev@ letting people know. I'll also open nominations today to give people a longer amount of time. Here is the google form: https://goo.gl/forms/WRVqwE1ePj3P2SIi2

**Note that TDC maintainers (everyone in a MAINTAINERS file across projects) maintainer may nominate up to two (2) candidates for election, except that only one (1) nominee may be employed by the TDC maintainer’s own company.**

**Comment by philips** [comment]
Today is Jan 16th 2017; Nominations Close today.

**Comment by caniszczyk** [comment]
Friendly ping for the @opencontainers/image-spec-maintainers @opencontainers/runtime-spec-maintainers @opencontainers/runtime-tools-maintainers @opencontainers/image-tools-maintainers 

So far 12 people have given me their list of nominations, so thank you for that.

**Comment by caniszczyk** [comment]
Thanks, 16 people have responded so far with a great set of candidates.

I will close nominations at the end of today UTC time.

I sent out a reminder email to all those who haven't voted too.

**Comment by RobDolinMS** [comment]
@caniszczyk After the close of nominations, will you be posting the list of all nominated candidates?

**Comment by caniszczyk** [comment]
@RobDolinMS I will post it later tonight here and the voting emails will go out to all qualified TDC maintainers.

**Comment by caniszczyk** [comment]
Here is the final list of candidates:

* Aleksa Sarai	(SUSE)
* Brendan Burns (Microsoft)
* Daniel Walsh (Red Hat)
* Dao Quang Minh Daniel (Huawei)
* Greg Kroah-Hartman	(Linux Foundation)
* Jonathan Boulle (CoreOS)
* Michael Crosby (Docker)
* Phil Estes (IBM)
* Qiang Huang (Huawei)
* Rob Dolin (Microsoft)
* Stephen Day (Docker)
* Tianon Gravi (Infosiftr)
* Tim Hockin (Google)
* Vincent Batts (Red Hat)
* Vishnu Kannan (Google)
* W. Trevor King (Independent)

The voting will happen via CIVS (http://civs.cs.cornell.edu/) and every official TDC maintainer (exists in a MAINTAINERS file will receive an email to do a ranking vote).

**Comment by caniszczyk** [comment]
Just as a heads up, I will start voting tomorrow.

I emailed the list of candidates to see if anyone wants to opt out from a nomination.

**Comment by thockin** [comment]
Appreciate the nomination - where's the summary of exactly what are the responsibilities and time commitment?

**Comment by caniszczyk** [comment]
@thockin the time commitment is fairly minimal, the TOB doesn't formally meet unless they decide to call a meeting (e.g., if a major conflict arises). I believe @philips or the rest of the @opencontainers/tob can speak to the level of commitment.

In terms of responsibilities: https://github.com/opencontainers/tob#technical-oversight-board-tob

> The TOB is responsible for managing conflicts, violations of procedures or guidelines and any cross-project or high-level issues that cannot be resolved in the TDC for OCI Projects. The TOB shall also be responsible for adding, removing or reorganizing OCI Projects.

More info found in the charter section 6: https://www.opencontainers.org/about/governance

In terms of mailing list activity, you can see the level of activity here (fairly minimal):
https://groups.google.com/a/opencontainers.org/forum/#!forum/tob

**Comment by wking** [comment]
On Tue, Jan 17, 2017 at 04:51:30PM -0800, Chris Aniszczyk wrote:
> I emailed the list of candidates to see if anyone wants to opt out
> from a nomination.

I'm happy to stand for election if folks want (and thanks for the
nomination, whoever that was), but I'm not sure I (or the other
non-maintainers: @estesp, @gregkh, @rhatdan, @RobDolinMS, and
@thockin) are eligible.  More on this in #24 to avoid distracting from
this election if folks don't want to get into it now.

**Comment by caniszczyk** [comment]
Sent out the CIVS poll to all maintainers, look for an email from Condorcet Internet Voting Service <civs@cs.cornell.edu>

cc: @opencontainers/image-spec-maintainers @opencontainers/runtime-spec-maintainers @opencontainers/runtime-tools-maintainers @opencontainers/image-tools-maintainers)

**Comment by caniszczyk** [comment]
Results are in, thanks to everyone who voted and took part in the process:

https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/uE7-41-fevA

The top 4 results are:
* Vincent Batts
* Michael Crosby
* Greg Kroah-Hartmann
* Vishnu Kannan

The process of electing a new TOB chair will start soon, which happens annually:
https://github.com/opencontainers/tob/issues/25
