### ISSUE TITLE
New project: opencontainers/go-digest

### ISSUE THREAD

**Issue by stevvooe** [opencontainers/tob#21]
https://github.com/opencontainers/image-spec/pull/486 introduces a dependency on a stable upstream implementation of https://github.com/docker/go-digest, which was recently broken out of the https://github.com/docker/distribution project.

This package has been instrumental in providing a strong hash-identity implementation in Go and I hope to extend this to OCI.

Let's support this by moving this into a https://github.com/opencontainers/go-digest project specifically oriented towards providing this functionality throughout the container ecosystem. While this package does support opencontainers/image-spec, it is broadly useful in other image formats or outside image formats. 

Having a solid, battle-proven, common digest implementation in OCI for use in and outside the image-spec will ensure long lasting security and interoperability throughout the container ecosystem.

Provisions:

1. https://github.com/docker/go-digest would become https://github.com/opencontainers/go-digest.
2. Maintainers would the current image-spec maintainers.
3. I, @stevvooe, will act as lead maintainer on this project.

@caniszczyk @philips

**Comment by caniszczyk** [comment]
SGTM, this would require 2/3 vote via @opencontainers/tob to formalize it as a project

We would also need a list of initial MAINTAINERS. We could opt on creating a project proposal similar to what the OCI Tools project did awhile ago for clarity: https://github.com/opencontainers/tob/blob/master/proposals/tools.md

**Comment by philips** [comment]
This proposal LGTM. Agreed MAINTAINERS seems critical, just mapping it to the image-spec would be fine with me but I would be fine with other arrangements as well under @stevvooe's discretion.

**Comment by stevvooe** [comment]
@caniszczyk @philips Thank you!

I would propose that the maintainers be the image-spec containers.

I'll volunteer to be "lead maintainer" of this package, if we have such a thing. If there are objections, please let me know.

The level activity on this project should be minimal, as it is fairly mature. If it wasn't clear for the proposal, https://github.com/docker/go-digest would be copied over and we would then update the front matter to match OCI project requirements.

**Comment by stevvooe** [comment]
I've update the description with details, so people know what they're voting on.

**Comment by crosbymichael** [comment]
LGTM

**Comment by caniszczyk** [comment]
@stevvooe I created a project proposal here: https://github.com/opencontainers/tob/issues/21

Feel free to update it with anymore info. We can call for a formal vote for it when @philips wants to do it via the TOB (hopefully soon before the holidays).

**Comment by stevvooe** [comment]
@caniszczyk I keep clicking that link and it keeps taking me back to this issue. I think you meant #22.

**Comment by caniszczyk** [comment]
@stevvooe you're right, sorry about that, fixed the ref

**Comment by philips** [comment]
@caniszczyk I will send a formal vote out to the TOB in a few minutes.

**Comment by philips** [comment]
proposal sent https://groups.google.com/a/opencontainers.org/forum/#!topic/tob/kplbAW5N9dc

**Comment by caniszczyk** [comment]
This vote has also definitely passed unanimously with 9/9 approving the new project transfer:

Brandon Philips: +1
Michael Crosby: +1
Dr. Diogo Monica: +1
Jason Bouzane: +1
Greg Kroah-Hartman: +1
John Gossman: +1
Pavel Emelyanov: +1
Chris Wright: +1
Vincent Batts: +1

I'll work with @stevvooe to xfer the repo later this week

**Comment by caniszczyk** [comment]
The migration has happened: https://github.com/opencontainers/go-digest

We still need to do some repo cleanup IMHO, thanks @stevvooe again.

FYI @opencontainers/tob
