### ISSUE TITLE
Can non-maintainers stand for TOB elections?

### ISSUE THREAD

**Issue by wking** [opencontainers/tob#24]
From the [charter][1]'s §6.e:

> Anyone may be elected to the TOB, regardless of whether the individual is an employee of an OCI Member, so long as they are an OCI TDC participant.

And from §5.b:

>  b. The OCI TDC has an established scope of work focused on:
>
>   …
>   viii. Creating, maintaining and enforcing governance guidelines for the TDC, approved by the maintainers, and which shall be posted visibly for the TDC. The guidelines shall cover the following:
>
>    1. establishing and defining roles and responsibilities (at a minimum, a role for committers or maintainers authorized to commit code to the codebase);
>    2. defining the process or requirements to take on a role in the TDC (e.g. how to become a contributor, or how to become a maintainer);
>    3. the process by which participants in the TDC may give up or be revoked of their roles (e.g. how to remove maintainers); the rules for decision making in the TDC; and the process by which participants in the TDC may give up or be revoked of their roles (e.g. how to remove maintainers); the rules for decision making in the TDC; and

As far as I'm aware, the only TDC role that any OCI Project has defined is “maintainer”.  So I think non-maintainers are not TDC participants, and are therefore excluded from standing for TOB election.

However, the charter is not clear on a number of points.  Perhaps my reading is missing the spirit of the charter and the charter-writers only intended that sentence to lift a potential OCI Member employee restriction.  The charter *is* clear that the current TDC maintainers will be doing the electing of this round, and since those are the same folks who have the power to induct new TDC maintainers/participants, I don't see how restricting the candidates to current TDC participants serves any purpose.  And for the OCI Member round of TOB elections, I don't see why OCI Members would want their candidate pool limited to current TDC participants, since they have no direct control over who that set of people is.

[1]: https://www.opencontainers.org/about/governance

**Comment by caniszczyk** [comment]
"OCI TDC participant" was purposefully vague, this could imply someone who has contributed code, discussion in an issue or to the technology via other means.

In this current election, the TDC maintainers get to nominate and vote on the 4 TOB spots. Next year, the TOB members will have their hand at 5 spots as the terms of 5 members ends. The idea was to be a balance between the membership and TDC maintainer community.

If the TOB wants to further clarify this they are welcome to and are empowered to, but at the moment, no one has come forward to do this.

Thanks for raising this though as it does point out an issue we may want to tackle if we go and update the charter at some point.

**Comment by wking** [comment]
On Tue, Jan 17, 2017 at 09:41:38PM -0800, Chris Aniszczyk wrote:
> "OCI TDC participant" was purposefully vague, this could imply
> someone who has contributed code, discussion in an issue or to the
> technology via other means.

Restricting TOB candidates to a purposefully vague set of people
doesn't seem very helpful to me.  I trust TDC Maintainers and TOB
Members to not nominate folks who have absolutely no interest in
containers ;).

> In this current election, the TDC maintainers get to nominate and
> vote on the 4 TOB spots. Next year, the TOB members will have their
> hand at 5 spots as the terms of 5 members ends. The idea was to be a
> balance between the membership and TDC maintainer community.

Yeah, this part makes sense to me.

> If the TOB wants to further clarify this they are welcome to and are
> empowered to, but at the moment, no one has come forward to do this.

I'm happy to work up a PR against the charter.  Filing those on my own
initiative hasn't been very productive in the past [1], so I'll leave
this alone for now, but if any TOB members are interested enough to
field a PR, but doesn't have time to work one up themselves, feel free
to reach out to me.

[1]: https://github.com/opencontainers/web/pull/3#issuecomment-136877478

**Comment by RobDolinMS** [comment]
Both voting groups (Trademark Board and Maintainers) elected non-maintainers to the TOB in early 2016 so I believe precedent has been set for non-maintainers to serve on the TOB.

**Comment by wking** [comment]
> ... so I believe precedent has been set for non-maintainers to serve on the TOB.

That's good.  I still think the language could be clarified, and then readers wouldn't have to look for precedence or decide whether the ambiguity was intentional.
