### ISSUE TITLE
TOB Chair Elections 2017

### ISSUE THREAD

**Issue by caniszczyk** [opencontainers/tob#25]
Now that the TOB Elections for 2017 are over, it's time to elect a new TOB chair:
https://github.com/opencontainers/tob/issues/20

**Comment by caniszczyk** [comment]
Hey @opencontainers/tob, if you're interested in running for TOB chair or are interested in nominating someone, please let me know here.

**Comment by caniszczyk** [comment]
I will leave the nomination period open until end of day Wednesday, Feb 1st.

**Comment by philips** [comment]
I would like to run for TOB chair and would be happy to continue the responsibilities of TOB Chair for another year. Thank you for letting me serve in this capacity for the last year.

**Comment by caniszczyk** [comment]
Friendly reminder @opencontainers/tob

**Comment by vbatts** [comment]
i'm game for @philips to chair. I'd nominate myself he didn't :wink:

**Comment by vishh** [comment]
+1 for @philips to be the chair.

**Comment by caniszczyk** [comment]
Since @philips was the only nominate candidate for TOB Chair, he wins by default and will serve another year as TOB Chair.

Thanks @opencontainers/tob
