### ISSUE TITLE
Consideration: moving selinux library out of runc into a new project

### ISSUE THREAD

**Issue by caniszczyk** [opencontainers/tob#27]
There's been a discussion in the OCI TDC about potentially moving the selinux library out of runc and into a new project (say something like opencontainers/libselinux)

I'm creating this issue as a placeholder while the OCI TDC finishes debating whether to move forward or not. If we move forward, we will consult the TOB and begin a formal project proposal.

cc: @mrunalp

**Comment by crosbymichael** [comment]
LGTM

**Comment by mrunalp** [comment]
We would like to name it `go-selinux`.
cc: @rhatdan @runcom

**Comment by runcom** [comment]
:+1: for what it's worth I've already created the project at https://github.com/runcom/go-selinux to have a look at how it would look like.

**Comment by rhatdan** [comment]
go-selinux is fine with me.

**Comment by caniszczyk** [comment]
Can you give me a list of maintainers for the project?

@rhatdan @runcom and who else? @crosbymichael ?

Thanks

**Comment by caniszczyk** [comment]
Also FYI @opencontainers/runc-maintainers

**Comment by caniszczyk** [comment]
I've added a draft project proposal here:
https://github.com/opencontainers/tob/pull/29

@mrunalp can you take a look at it and fill in the missing obvious bits?
