### ISSUE TITLE
Update Code of Conduct

### ISSUE THREAD

**Issue by caniszczyk** [opencontainers/tob#31]
After speaking with @philips, we will do a proposed update of the OCI Code of Conduct to be more modern with the state of the art in this field. The LF best practice moving forward is having the community be the focal point of the enforcement (usually via a committee of some type). We can decide to just delegate this to the TOB, a subset of the TOB or a newly formed code of conduct committee.

Note, this will be a post v1.0 activity

**Comment by vbatts** [comment]
Agreeing that our CoC could handle a review, are there particular points for this process to kick off?

**Comment by sudo-bmitch** [comment]
Revisiting this very old issue, should we update;

https://github.com/opencontainers/.github/blob/main/CODE_OF_CONDUCT.md

with the latest upstream guidelines currently available at:

https://www.contributor-covenant.org/version/2/1/code_of_conduct/

**Comment by samuelkarp** [comment]
Should we open a PR and have TOB vote on the actual textual change of the PR?

**Comment by sudo-bmitch** [comment]
I've opened https://github.com/opencontainers/.github/pull/61 and will send a vote to the list shortly.

**Comment by sudo-bmitch** [comment]
This update has been approved by the ToB and merged in https://github.com/opencontainers/.github/pull/61
