### ISSUE TITLE
OCI Election 2018: Elect TOB Chair

### ISSUE THREAD

**Issue by caniszczyk** [opencontainers/tob#40]
Now that the OCI TOB is established for 2018, we need to elect a new chair.

**Comment by caniszczyk** [comment]
> i. The TOB shall elect a TOB Chair. The nominee with the most votes from the TOB members shall win the Chair position for a term of one (1) year. In the event of a tie vote, a random selection process (e.g. coin toss) shall be used to determine the winner. The TOB Chair shall have the responsibility to call meetings of the TOB and set TOB meeting agendas with input from TOB members.

**Comment by caniszczyk** [comment]
Hey @opencontainers/tob, I will be opening the call for nominations for the OCI TOB Chair position detailed above. Last year, we only had one volunteer via @philips. 

I will close nominations EOD Friday Feb 2nd (PT time). If we have more than one volunteer, I will run elections the following week.

**Comment by crosbymichael** [comment]
How do you submit nominations?

**Comment by caniszczyk** [comment]
@crosbymichael just nominate yourself on this thread

**Comment by crosbymichael** [comment]
Ok, thanks.

I'll volunteer/nominate myself this time around to help out for this position.

**Comment by caniszczyk** [comment]
We are going to hold on electing the TOB chair until the final TOB slot is filled due to https://github.com/opencontainers/tob/issues/42

**Comment by philips** [comment]
I would like to nominate @mrunalp for the TOB chair.

Mrunal was instrumental in ensuring that meetings ran regularly and had agenda's in the early days of the OCI. This along with his deep technical expertise will serve the TOB well.

**Comment by mrunalp** [comment]
I accept the nomination. Thanks!

**Comment by caniszczyk** [comment]
I kicked off the vote to the 9 @opencontainers/tob via CIVS.

I will close the election Monday Feb 19th EOD PT time (unless everyone votes quickly)

Thanks!

**Comment by caniszczyk** [comment]
Alright too funny @opencontainers/tob, we have a tie because one person decided to rank both of you equally:
https://civs.cs.cornell.edu/cgi-bin/results.pl?num_winners=1&id=E_af39730304a12a1d&algorithm=runoff

I will do a coin toss on Monday when I'm back home from traveling.

**Comment by caniszczyk** [comment]
I'm doing the coin toss today, going to assign Heads and Tails based on alphabetical order:

* Michael Crosby (@crosbymichael): Heads
* Mrunal Patel (@mrunalp): Tails

**Comment by caniszczyk** [comment]
It's Heads! 

@crosbymichael wins the coin toss, congrats, the blog post announcing the OCI TOB will go out tomorrow.

![ezgif-4-9dc60d9594](https://user-images.githubusercontent.com/63777/36393550-b0439bb0-1575-11e8-8722-c68947f0a595.gif)

**Comment by philips** [comment]
Congrats @crosbymichael

**Comment by mataneja** [comment]
congratulations @crosbymichael!
