### ISSUE TITLE
Investigate OCI TOB due to Red Hat + CoreOS acquisition

### ISSUE THREAD

**Issue by caniszczyk** [opencontainers/tob#42]
Red Has announced an agreement to acquire CoreOS:
https://www.redhat.com/en/about/press-releases/red-hat-acquire-coreos-expanding-its-kubernetes-and-containers-leadership

The @opencontainers/tob has certain rules in place to ensure only a certain number of representatives can be from one entity:

> e. The TOB shall be composed of nine (9) individuals elected for their expertise, contribution to the advancement of container technologies and are considered to be thought leaders in the OCI ecosystem. Anyone may be elected to the TOB, regardless of whether the individual is an employee of an OCI Member, so long as they are an OCI TDC participant. A TOB member is elected as an individual and not as a representative of his or her employer. No more than two (2) TOB members may be employed by the same entity or its affiliates. Affiliates shall be defined as entities owning 50% or more of an entity, or owned by or under common ownership with each other. TOB members may not designate alternative representatives. 

I will reach out to Red Hat to see which two candidates they desire to keep on the TOB. After that is done, I will run another election for the newly available TOB slot.

My proposed timeline:
* Nomination Period: Jan 31st - Feb 6th (end of day PT)
* Elections: Feb 7th - Feb 12th (end of day PT)
* Results: Feb 13th

**Comment by wking** [comment]
On Wed, Jan 31, 2018 at 01:04:48PM +0000, Chris Aniszczyk wrote:
> After that is done, I will run another election for the newly
> available TOB slot.

With @philips and @mrunalp just elected [1], I was wondering if we
could recycle the ordered rankings from #33.  But Red Hat may decide
to drop @vbatts (who wasn't up for election), and the recent vote had
a tie for 6th place anyway [2], so we'll need a new election no matter
what.

[1]: https://github.com/opencontainers/tob/issues/33#issuecomment-361335273
[2]: https://civs.cs.cornell.edu/cgi-bin/results.pl?num_winners=6&id=E_f742dffe55b0bb1b&algorithm=runoff

**Comment by caniszczyk** [comment]
@wking thanks for the suggestion but the election already has happened and the announcement to intend to acquire happened afterwards. It is only fair to run a new election given the chance of circumstances (we also had a tie for the 6th position in the previous election).

**Comment by wking** [comment]
On Wed, Jan 31, 2018 at 10:39:18AM -0800, Chris Aniszczyk wrote:
> @wking thanks for the suggestion but the election already has happened…

Yup.  I'm not sure how much drift there has been in OCI Member
preferences over the past week, but I agree that drift is possible.

> … we also had a tie for the 6th position in the previous election…

And this sinks the “recycle the old vote” approach on it's own, so we
don't even have to decide whether or not we'd be ok with a recycle.  I
just posted my comment (pointing out that a recycle was not possible
in this case) to save anyone else from having to look that up.

**Comment by caniszczyk** [comment]
I've reached out to Red Hat and they will leave @mrunalp and @vbatts on the TOB, with @philips relinquishing his seat. We will move forward with the election with the schedule above for the newly available seat.

Thank you so much @philips for being part of OCI since the beginning and getting it to where it is today.

**Comment by philips** [comment]
Thanks everyone! OCI is in good hands with @mrunalp, @vbatts, and the rest of the OCI community.

**Comment by caniszczyk** [comment]
FYI: The election has started for the final nominees for the last TOB slot, we have 4 candidates. All OCI members have been sent an election ballot to vote on for four candidates. We will announce results on Feb 13th:

Mike Brown (IBM) is a Software Engineer, IBMer, Inventor, Coach, PC Gamer, and Proud Father. He works on Open Container Initiative (OCI) projects ranging from the runtime and image specifications to products that are implementing OCI such as Docker, Containerd, and Kubernetes. Mike is currently a maintainer for containerd focusing on the Kubernetes CRI integration project which uses the OCI runtime and image specifications. Mike has worked as a Software Engineer, lead, and standards body representative on projects ranging from Operating Systems, Java Virtual Machines, Web Browsers, and Middleware Stacks to Insurance and Finance products.

Taylor Brown (Microsoft) is a Principal Program Management Lead in the Base division of the Windows and Devices Group at Microsoft. His over 15-year engineering career at Microsoft has encompassed development and program management roles focused on virtualization technologies including Virtual PC, Virtual Server, Hyper-V, Windows containers and the Windows Subsystem for Linux with stents on ACPI/power management and the Microsoft Smart Watch (SPOT) teams. As the Lead Program Manager for Windows containers he has been instrumental in bringing Docker, Kubernetes and other open source technologies to Windows.

Qiang Huang (Huawei) is the OS and container architect who has been working on container and kernel area from 2010 in Huawei. He has been an active Docker contributor since 2014 and joined OCI community when it's established in 2015. Now Qiang is the maintainer in runtime-spec, runc and runtime-tools projects. He is familiar with container industry and keen on container technologies, he promoted commercial landing of container technology in Huawei and managed the container team to work tightly with OCI.

Aleksa Sarai (SUSE) is an undergraduate at the University of Sydney, and works on the Kubernetes core team at SUSE. He has been working on and helping maintain container runtimes for several years, and has a passion for working on Free Software and open standards. Notable examples of his work include the rootless containers support in runc (as well as work with other communities to integrate rootless containers into their projects), and developing tools like umoci to operate with OCI images.

**Comment by caniszczyk** [comment]
Taylor Brown will take the last OCI TOB slot:

https://civs.cs.cornell.edu/cgi-bin/results.pl?num_winners=1&id=E_1b4597deb3a12aaa&algorithm=runoff

**Comment by caniszczyk** [comment]
We will post an official blog post next week on the newly elected @opencontainers/tob
