### ISSUE TITLE
Elect OCI TOB Chair for 2019

### ISSUE THREAD

**Issue by caniszczyk** [opencontainers/tob#54]
Hey @opencontainers/tob, I will be opening the call for nominations for the OCI TOB Chair position detailed above. Last year, we only had one volunteer via @crosbymichael

**Comment by caniszczyk** [comment]
I will close nominations EOD Friday Feb 8th (PT time). If we have more than one volunteer, I will run elections the following week. Hey @crosbymichael since you've done a great job, I assume you want to re-nominate yourself :)?

**Comment by vbatts** [comment]
I'll volunteer myself as well

**Comment by crosbymichael** [comment]
Yes, I will run again to continue the work ;)

**Comment by caniszczyk** [comment]
Awesome ping @opencontainers/tob 

I will close nominations end of this week, Fri midnight PT time

**Comment by caniszczyk** [comment]
I will the open CIVS up next week for a vote :)

**Comment by caniszczyk** [comment]
CIVS poll is out @opencontainers/tob

**Comment by caniszczyk** [comment]
final reminder on poll, closes tomorrow @opencontainers/tob

**Comment by caniszczyk** [comment]
There was a tie for the OCI TOB Chair, I'm going to flip a coin this afternoon at 2pm:

https://civs.cs.cornell.edu/cgi-bin/results.pl?id=E_ca0ada39b92ab119

Batts (H), Crosby (T)

**Comment by crosbymichael** [comment]
Ahh, the coin toss, two times in a row :)

**Comment by caniszczyk** [comment]
It was (T), Crosby wins, thanks, we will publish a blog post soon!

![ezgif-4-0cab103fb4f3](https://user-images.githubusercontent.com/63777/52504712-de932580-2bae-11e9-8abe-ee249395df34.gif)

**Comment by taylorb-microsoft** [comment]
Congratulations @crosbymichael

**Comment by vbatts** [comment]
dangling chads!
Also, congrats @crosbymichael !
