### ISSUE TITLE
Add artifact-distribution repository

### ISSUE THREAD

**Issue by SteveLasker** [opencontainers/tob#59]
Proposal is to create a separate repository to cover Artifact Distribution.
Accounts for: [Artifact registry support #65](https://github.com/opencontainers/distribution-spec/pull/65#issuecomment-510249101)

The new repository would explain:
- how distribution is used to store additional types. 
- guidance to registry owners for how to parse artifact types
- guidance to artifact authors for how manifests and index are used to define new types

With artifacts defined here, the distribution spec can be updated to remove references to images, making it more about storing index and manifest references to layers. 

Proposed repository name:
`artifact-spec`

**Comment by caniszczyk** [comment]
Thanks @SteveLasker, can you do a PR?

See this as an example:
https://github.com/opencontainers/tob/blob/master/proposals/distribution.md

RFC @opencontainers/tob

**Comment by estesp** [comment]
My bad; I thought a request for a new repo was an issue, so directed @SteveLasker to do an issue first.

**Comment by dmcgowan** [comment]
I might have given the wrong suggestion as well, but looking at the other proposals, this would fit there too.

I think this would replace #57 and I don't think we should refer to as a spec as that has versioning implications that wouldn't apply here. We can discuss in the call, but maybe `manifest-types` or `manifest-artifacts` such that the scope of the repo is listing the known media types used by manifests and the relationship/structure of the artifacts which use them.

**Comment by caniszczyk** [comment]
this was done: https://github.com/opencontainers/artifacts
