### ISSUE TITLE
OCI TOB Chair 2020

### ISSUE THREAD

**Issue by caniszczyk** [opencontainers/tob#62]
We need to elect an OCI TOB Chair.

The seat is currently hold by @crosbymichael.

**Comment by caniszczyk** [comment]
We will have nominations open until Jan 31st for the TOB

**Comment by caniszczyk** [comment]
pining the @opencontainers/tob if anyone is interested in running for the TOB, if not, @crosbymichael will remain TOB chair :)

**Comment by vbatts** [comment]
:+1:

**Comment by estesp** [comment]
I’ll put my name in. Thanks!

**Comment by vbatts** [comment]
Another suitable candidate!

-------- Original Message --------

**Comment by SteveLasker** [comment]
what does it entail?

On Jan 31, 2020, at 6:06 AM, Vincent Batts <notifications@github.com> wrote:

﻿Another suitable candidate!

-------- Original Message --------

**Comment by caniszczyk** [comment]
We will do an election if there is more than one candidate.

Right now, it's just @estesp 

@crosbymichael do you want to run again or bow out?

**Comment by caniszczyk** [comment]
@SteveLasker also the chair based on the charter...

"i. The TOB shall elect a TOB Chair. The nominee with the most votes from the TOB members shall win the Chair position for a term of one (1) year. In the event of a tie vote, a random selection process (e.g. coin toss) shall be used to determine the winner. The TOB Chair shall have the responsibility to call meetings of the TOB and set TOB meeting agendas with input from TOB members."

It's not SUPER exciting but an important role based on how we have defined the community. The OCI TOB doesn't meet often and only when we have new projects to approve.

**Comment by cyphar** [comment]
@caniszczyk I'll throw my hat in too.

**Comment by caniszczyk** [comment]
@cyphar 

Thanks, I sent the OCI TOB a CIVS poll that closes Thu EOD PT time.

**Comment by SteveLasker** [comment]
👍

**Comment by caniszczyk** [comment]
@estesp is TOB Chair for 2020, we will make a formal announcement next week:
https://civs.cs.cornell.edu/cgi-bin/results.pl?num_winners=1&id=E_70c3a32a0756e3f8&algorithm=runoff
