### ISSUE TITLE
GOVERNANCE: Scope table: drop/rewrite/replace?

### ISSUE THREAD

**Issue by estesp** [opencontainers/tob#73]
Per many discussions, and most recently in the @opencontainers/tob call, the scope table is clearly out of date and not applicable to the current state of the OCI.

Options are drop it with the governance update work in #72, or rewrite it/replace it with a prose version that flows from a clear expression of why the OCI exists followed by a list of projects and their reasons for existing in the OCI universe of projects. Feedback is that there is no clear, understandable place to understand these core ideas and to differentiate newcomer's understanding of OCI vs. CNCF, as one example.

Related: #10 (would potentially be superseded by a rewrite as a non-table and would not require any special rules to update)

**Comment by caniszczyk** [comment]
I moved the OCI Charter to GitHub:
https://github.com/opencontainers/tob/blob/master/CHARTER.md

I will do the same for the scope table.

**Comment by estesp** [comment]
See #74

**Comment by estesp** [comment]
Closing with #74
