### ISSUE TITLE
OCI TOB Chair 2021

### ISSUE THREAD

**Issue by caniszczyk** [opencontainers/tob#92]
We need to elect an OCI TOB Chair starting next week

The seat is currently held by @estesp :)

We will have nominations open until Feb 3rd EOD PT time for the TOB

**Comment by caniszczyk** [comment]
friendly ping @opencontainers/tob 

Let me know if you're interested in running again @estesp, you've done a great job! :)

**Comment by estesp** [comment]
I'm definitely willing to run again. Thanks!

**Comment by cyphar** [comment]
I'll throw my hat in again, though @estesp did a great job last time too. :D

**Comment by amye** [comment]
Last call on this, @opencontainers/tob -- I'll be putting together an election at EOD with the candidates.

**Comment by caniszczyk** [comment]
Thanks @amye, run the election until noon Monday PT, should be an easy one ;)

**Comment by amye** [comment]
Expanding slightly, noon Tuesday PT is when elections will close.

**Comment by amye** [comment]
Poll is closed, Phil Estes is our chair for this year!

**Comment by caniszczyk** [comment]
Thanks @amye 
https://civs.cs.cornell.edu/cgi-bin/results.pl?num_winners=1&id=E_e9dc7752236c0526&rkey=fcefa208330bc1a2&algorithm=runoff

**Comment by jonjohnsonjr** [comment]
🎉  Congrats @estesp 🎉
